import { NextResponse } from "next/server";
import PptxGenJS from "pptxgenjs";
import { LESSON_PLAN_SECTIONS } from "@/lib/lesson-plan";
import type { LessonPlanPptxPayload } from "@/lib/lesson-plan";

export const runtime = "nodejs";

const COLORS = {
  blue: "1E40AF",
  lightBlue: "DBEAFE",
  white: "FFFFFF",
  dark: "0F172A",
  muted: "334155",
};

function sanitizeFileName(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 70);
}

function validatePayload(payload: LessonPlanPptxPayload) {
  if (
    !payload.subject?.trim() ||
    !payload.grade?.trim() ||
    !payload.topic?.trim() ||
    !payload.lessonPlan
  ) {
    return false;
  }

  return LESSON_PLAN_SECTIONS.every(
    (section) =>
      typeof payload.lessonPlan[section] === "string" &&
      payload.lessonPlan[section].trim().length > 0,
  );
}

export async function POST(req: Request) {
  let payload: LessonPlanPptxPayload;
  try {
    payload = (await req.json()) as LessonPlanPptxPayload;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  if (!validatePayload(payload)) {
    return NextResponse.json(
      { error: "Invalid lesson plan payload for PowerPoint generation." },
      { status: 400 },
    );
  }

  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Teacher AI Studio";
  pptx.company = "Teacher AI Studio";
  pptx.subject = `${payload.subject} - ${payload.topic}`;
  pptx.title = `Lesson Plan - ${payload.topic}`;

  for (const section of LESSON_PLAN_SECTIONS) {
    const slide = pptx.addSlide();
    const content = payload.lessonPlan[section];

    slide.background = { color: COLORS.white };

    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.333,
      h: 0.95,
      fill: { color: COLORS.blue },
      line: { color: COLORS.blue },
    });

    slide.addText(section, {
      x: 0.6,
      y: 0.28,
      w: 9.7,
      h: 0.45,
      fontSize: 25,
      bold: true,
      color: COLORS.white,
      fontFace: "Calibri",
    });

    slide.addText(`${payload.subject} | ${payload.grade} | ${payload.topic}`, {
      x: 0.65,
      y: 1.2,
      w: 12,
      h: 0.3,
      fontSize: 12,
      color: COLORS.muted,
      fontFace: "Calibri",
    });

    slide.addShape(pptx.ShapeType.roundRect, {
      x: 0.65,
      y: 1.65,
      w: 12.05,
      h: 5.4,
      rectRadius: 0.08,
      fill: { color: COLORS.lightBlue, transparency: 76 },
      line: { color: COLORS.lightBlue, pt: 1 },
    });

    slide.addText(content, {
      x: 0.9,
      y: 1.92,
      w: 11.5,
      h: 4.85,
      fontSize: 18,
      color: COLORS.dark,
      valign: "top",
      fit: "shrink",
      breakLine: true,
      fontFace: "Calibri",
    });

    slide.addShape(pptx.ShapeType.line, {
      x: 0.65,
      y: 7.15,
      w: 12.05,
      h: 0,
      line: { color: COLORS.blue, pt: 1 },
    });

    slide.addText("Generated by Teacher AI Studio", {
      x: 0.65,
      y: 7.2,
      w: 12,
      h: 0.2,
      fontSize: 10,
      color: COLORS.muted,
      align: "right",
      fontFace: "Calibri",
    });
  }

  const fileName = sanitizeFileName(
    `${payload.grade}-${payload.subject}-${payload.topic}-lesson-plan`,
  );
  const buffer = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;

  return new NextResponse(buffer, {
    status: 200,
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "Content-Disposition": `attachment; filename="${fileName || "lesson-plan"}.pptx"`,
      "Cache-Control": "no-store",
    },
  });
}
