import { NextResponse } from "next/server";
import PptxGenJS from "pptxgenjs";
import {
  getLessonPlanDisplayOrder,
  getSectionTabLabel,
  isLegacyLessonPlan,
  isTeacherPackagePlan,
} from "@/lib/lesson-plan";
import type { LessonPlanPptxPayload } from "@/lib/lesson-plan";

export const runtime = "nodejs";

const COLORS = {
  blue: "1E40AF",
  lightBlue: "DBEAFE",
  white: "FFFFFF",
  dark: "0F172A",
  muted: "334155",
};

function sanitizeFileName(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 70);
}

function validatePayload(payload: LessonPlanPptxPayload) {
  if (
    !payload.subject?.trim() ||
    !payload.grade?.trim() ||
    !payload.topic?.trim() ||
    !payload.lessonPlan
  ) {
    return false;
  }

  return (
    isTeacherPackagePlan(payload.lessonPlan) || isLegacyLessonPlan(payload.lessonPlan)
  );
}

export async function POST(req: Request) {
  let payload: LessonPlanPptxPayload;
  try {
    payload = (await req.json()) as LessonPlanPptxPayload;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  if (!validatePayload(payload)) {
    return NextResponse.json(
      { error: "Invalid lesson plan payload for PowerPoint generation." },
      { status: 400 },
    );
  }

  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "EduPlan AI";
  pptx.company = "EduPlan AI";
  pptx.subject = `${payload.subject} - ${payload.topic}`;
  pptx.title = `Teacher package — ${payload.topic}`;

  const sectionOrder = getLessonPlanDisplayOrder(payload.lessonPlan);

  // Title slide — full deck overview
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: COLORS.white };
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 13.333,
    h: 2.2,
    fill: { color: COLORS.blue },
    line: { color: COLORS.blue },
  });
  titleSlide.addText("EduPlan AI", {
    x: 0.75,
    y: 0.55,
    w: 11.8,
    h: 0.5,
    fontSize: 14,
    color: COLORS.white,
    fontFace: "Calibri",
  });
  titleSlide.addText("Complete teacher package", {
    x: 0.75,
    y: 1.0,
    w: 11.8,
    h: 0.9,
    fontSize: 32,
    bold: true,
    color: COLORS.white,
    fontFace: "Calibri",
  });
  titleSlide.addText(payload.topic, {
    x: 0.75,
    y: 2.55,
    w: 11.8,
    h: 0.55,
    fontSize: 22,
    color: COLORS.dark,
    fontFace: "Calibri",
  });
  titleSlide.addText(`${payload.subject}  ·  ${payload.grade}`, {
    x: 0.75,
    y: 3.25,
    w: 11.8,
    h: 0.4,
    fontSize: 14,
    color: COLORS.muted,
    fontFace: "Calibri",
  });
  titleSlide.addText(
    `This deck includes ${sectionOrder.length} section slide(s): ${sectionOrder.map((s) => getSectionTabLabel(s)).join(" · ")}`,
    {
      x: 0.75,
      y: 4.1,
      w: 11.5,
      h: 2.2,
      fontSize: 13,
      color: COLORS.dark,
      valign: "top",
      fontFace: "Calibri",
    },
  );
  titleSlide.addText("Generated by EduPlan AI", {
    x: 0.75,
    y: 7.15,
    w: 12,
    h: 0.25,
    fontSize: 10,
    color: COLORS.muted,
    align: "right",
    fontFace: "Calibri",
  });

  for (const section of sectionOrder) {
    const slide = pptx.addSlide();
    const content = payload.lessonPlan[section];

    slide.background = { color: COLORS.white };

    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.333,
      h: 0.95,
      fill: { color: COLORS.blue },
      line: { color: COLORS.blue },
    });

    const displayTitle = getSectionTabLabel(section);

    slide.addText(displayTitle, {
      x: 0.6,
      y: 0.28,
      w: 9.7,
      h: 0.45,
      fontSize: 25,
      bold: true,
      color: COLORS.white,
      fontFace: "Calibri",
    });

    slide.addText(`${payload.subject} | ${payload.grade} | ${payload.topic}`, {
      x: 0.65,
      y: 1.08,
      w: 12,
      h: 0.28,
      fontSize: 11,
      color: COLORS.muted,
      fontFace: "Calibri",
    });

    slide.addText(`Source field: ${section}`, {
      x: 0.65,
      y: 1.36,
      w: 12,
      h: 0.22,
      fontSize: 9,
      color: COLORS.muted,
      fontFace: "Calibri",
    });

    slide.addShape(pptx.ShapeType.roundRect, {
      x: 0.65,
      y: 1.68,
      w: 12.05,
      h: 5.35,
      rectRadius: 0.08,
      fill: { color: COLORS.lightBlue, transparency: 76 },
      line: { color: COLORS.lightBlue, pt: 1 },
    });

    slide.addText(content, {
      x: 0.9,
      y: 1.94,
      w: 11.5,
      h: 4.9,
      fontSize: 18,
      color: COLORS.dark,
      valign: "top",
      fit: "shrink",
      breakLine: true,
      fontFace: "Calibri",
    });

    slide.addShape(pptx.ShapeType.line, {
      x: 0.65,
      y: 7.15,
      w: 12.05,
      h: 0,
      line: { color: COLORS.blue, pt: 1 },
    });

    slide.addText("Generated by EduPlan AI", {
      x: 0.65,
      y: 7.2,
      w: 12,
      h: 0.2,
      fontSize: 10,
      color: COLORS.muted,
      align: "right",
      fontFace: "Calibri",
    });
  }

  const fileName = sanitizeFileName(
    `${payload.grade}-${payload.subject}-${payload.topic}-teacher-package`,
  );
  const buffer = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;

  return new NextResponse(new Uint8Array(buffer), {
    status: 200,
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "Content-Disposition": `attachment; filename="${fileName || "lesson-plan"}.pptx"`,
      "Cache-Control": "no-store",
    },
  });
}
