export type PdfContentSection = {
  heading: string;
  content: string;
};

export type PdfGenerateOptions = {
  sections: PdfContentSection[];
  subject: string;
  grade: string;
  topic: string;
  curriculumType?: string;
  teacherName?: string;
  teachingStrategy?: string;
};

/** Strip the start/end sentinel markers that the AI embeds in section text. */
function cleanContent(text: string): string {
  return text
    .replace(/^[A-Z][A-Z ]+START\r?\n?/m, "")
    .replace(/\r?\n?[A-Z][A-Z ]+END\s*$/m, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function safePart(s: string, maxLen: number): string {
  return s.replace(/[^a-zA-Z0-9]/g, "").slice(0, maxLen);
}

/**
 * Generates a professional PDF from lesson plan content and triggers browser download.
 * Uses jsPDF loaded via dynamic import so it doesn't increase the main bundle.
 */
export async function generateLessonPdf(opts: PdfGenerateOptions): Promise<void> {
  // Dynamic import keeps jsPDF (~350 KB) out of the initial bundle.
  const { jsPDF } = await import("jspdf");

  // ── Color palette ────────────────────────────────────────────────────────────
  const C_TEAL: [number, number, number] = [0, 198, 167];
  const C_NAVY: [number, number, number] = [10, 22, 40];
  const C_GRAY: [number, number, number] = [107, 114, 128];
  const C_TEXT: [number, number, number] = [55, 65, 81];
  const C_RULE: [number, number, number] = [220, 228, 235];

  // ── Page geometry (mm) ───────────────────────────────────────────────────────
  const PW = 210;
  const PH = 297;
  const ML = 20;          // margin left
  const MR = 20;          // margin right
  const CW = PW - ML - MR; // content width = 170 mm
  const HEADER_BOTTOM = 17;
  const CONTENT_TOP = 22;
  const FOOTER_Y = PH - 8;
  const CONTENT_BOTTOM = FOOTER_Y - 5;

  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

  let page = 1;
  let y = CONTENT_TOP;

  /** Approximate line height in mm for a given font size (pt). */
  const lh = (fs: number) => fs * 0.42;

  const setColor = (rgb: [number, number, number]) =>
    doc.setTextColor(rgb[0], rgb[1], rgb[2]);

  const setDraw = (rgb: [number, number, number]) =>
    doc.setDrawColor(rgb[0], rgb[1], rgb[2]);

  // ── Header ───────────────────────────────────────────────────────────────────
  const drawHeader = () => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    setColor(C_TEAL);
    doc.text("Layah", ML, 12);

    const dateStr = new Date().toLocaleDateString("en-GB", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    setColor(C_GRAY);
    doc.text(dateStr, PW - MR, 12, { align: "right" });

    setDraw(C_TEAL);
    doc.setLineWidth(0.45);
    doc.line(ML, HEADER_BOTTOM, PW - MR, HEADER_BOTTOM);
  };

  // ── Footer ───────────────────────────────────────────────────────────────────
  const drawFooter = (n: number) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    setColor(C_GRAY);
    doc.text("Generated by Layah — layah.in", ML, FOOTER_Y);
    doc.text(`Page ${n} of {nb}`, PW - MR, FOOTER_Y, { align: "right" });
  };

  // ── Page-break guard ─────────────────────────────────────────────────────────
  const ensureSpace = (neededMm: number) => {
    if (y + neededMm > CONTENT_BOTTOM) {
      drawFooter(page);
      doc.addPage();
      page++;
      drawHeader();
      y = CONTENT_TOP;
    }
  };

  // ── Text rendering helper ────────────────────────────────────────────────────
  const addWrappedText = (
    text: string,
    fs: number,
    bold: boolean,
    color: [number, number, number],
    indentMm = 0,
    spacingAfterMm = 1.5,
  ) => {
    const lines = doc.splitTextToSize(text, CW - indentMm) as string[];
    const lineHeight = lh(fs);
    for (const line of lines) {
      ensureSpace(lineHeight + 0.5);
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.setFontSize(fs);
      setColor(color);
      doc.text(line, ML + indentMm, y);
      y += lineHeight;
    }
    y += spacingAfterMm;
  };

  // ────────────────────────────────────────────────────────────────────────────
  // First-page header
  drawHeader();

  // ── Title block ──────────────────────────────────────────────────────────────
  if (opts.teacherName?.trim()) {
    addWrappedText(opts.teacherName.trim(), 12, true, C_NAVY, 0, 2);
  }

  const titleLine = [opts.subject, opts.grade, opts.topic].filter(Boolean).join("  |  ");
  addWrappedText(titleLine, 11, true, C_NAVY, 0, 2);

  if (opts.curriculumType?.trim()) {
    addWrappedText(`Curriculum: ${opts.curriculumType.trim()}`, 9, false, C_GRAY, 0, 1);
  }

  if (opts.teachingStrategy?.trim()) {
    addWrappedText(`Teaching Strategy: ${opts.teachingStrategy.trim()}`, 9, false, C_GRAY, 0, 1);
  }

  // Teal divider below title block
  y += 2;
  setDraw(C_TEAL);
  doc.setLineWidth(0.35);
  doc.line(ML, y, PW - MR, y);
  y += 6;

  // ── Content sections ─────────────────────────────────────────────────────────
  for (let i = 0; i < opts.sections.length; i++) {
    const section = opts.sections[i]!;
    const body = cleanContent(section.content);
    if (!body) continue;

    // Section heading — always starts with at least 20 mm of space
    ensureSpace(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11.5);
    setColor(C_NAVY);
    doc.text(section.heading, ML, y);
    y += lh(11.5) + 1;

    // Short teal accent line under heading
    setDraw(C_TEAL);
    doc.setLineWidth(0.4);
    doc.line(ML, y, ML + 45, y);
    y += 4;

    // Body text — line-by-line so page breaks work correctly
    const bodyLines = doc.splitTextToSize(body, CW) as string[];
    const bodyLineH = lh(9.5);
    for (const line of bodyLines) {
      ensureSpace(bodyLineH + 0.5);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      setColor(C_TEXT);
      doc.text(line, ML, y);
      y += bodyLineH;
    }

    // Light grey separator between sections (not after the last one)
    if (i < opts.sections.length - 1) {
      y += 5;
      ensureSpace(3);
      setDraw(C_RULE);
      doc.setLineWidth(0.2);
      doc.line(ML, y, PW - MR, y);
      y += 6;
    }
  }

  // ── Footer on last page & total-page replacement ─────────────────────────────
  drawFooter(page);
  doc.putTotalPages("{nb}");

  // ── Trigger download ──────────────────────────────────────────────────────────
  const dateTag = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const filename = [
    "Layah",
    safePart(opts.subject, 15),
    safePart(opts.grade, 10),
    safePart(opts.topic, 20),
    dateTag,
  ]
    .filter(Boolean)
    .join("_") + ".pdf";

  doc.save(filename);
}
