/**
 * PPT deck images — generated once during lesson-plan creation (not on download).
 *
 * Provider policy is explicit and typed rather than implied by scattered conditionals. Four
 * slides are **Fal-required**: Starter Activity, Differentiated Activity and Mini Plenary,
 * UAE / Real-Life Cross-Curricular Connection, and Extended Task. Those never fall back to a
 * Pexels stock photo — if Fal cannot produce an image the slide renders without one and the
 * failure is recorded, because a stock photo silently standing in for a generated illustration
 * is precisely the bug this policy exists to prevent.
 *
 * Every other image slide is **Fal-preferred**: Fal first, Pexels only if Fal fails and the
 * slide has a meaningful photo query.
 */

import * as Sentry from "@sentry/nextjs";
import { getFalCredentials } from "@/lib/fal-flux-section-images";
import { isUaeCurriculumFramework } from "@/lib/curriculum-framework";
import { logPexelsEnvStatus, resolvePexelsApiKey } from "@/lib/image-api-env";
import { STRUCTURED_LESSON_DECK_SLIDE_COUNT } from "@/lib/ppt-structured-lesson";
import { fetchPexelsUniqueLandscapeUrl } from "@/lib/pexels-images";
import {
  generateLessonPptFluxImageDeduped,
  getFalPptCircuitOpenReason,
  type FalImageFailureKind,
  type LessonPptFluxSlot,
  type PptSlideImageMeta,
} from "@/lib/fal-ppt-slide-images";

export type PptDeckImageMeta = PptSlideImageMeta & {
  curriculumFramework?: string;
  /** Per-deck-index lesson content, used to make Fal prompts contextually specific. */
  slideContentByIndex?: (string | null)[];
};

/** Which provider is allowed to serve a given slide. */
export type SlideImageProviderPolicy = "fal-required" | "fal-preferred";

/** Deck indices whose images must be generated by Fal AI and never substituted with stock. */
export const FAL_REQUIRED_DECK_INDICES = [1, 6, 7, 9] as const;

const PEXELS_SLIDE_LABELS: Record<number, string> = {
  0: "slide-1-title",
  1: "slide-2-starter",
  7: "slide-8-connection",
  8: "slide-9-plenary",
  9: "slide-10-extended",
};

function titleSlidePexelsQuery(m: PptDeckImageMeta): string {
  const subject = m.subject.trim().toLowerCase().replace(/\s+/g, " ");
  return subject ? `${subject} education` : "education";
}

type DeckImageSpec = {
  idx: number;
  slideNumber1Based: number;
  falSlot: LessonPptFluxSlot;
  provider: SlideImageProviderPolicy;
  /** Only ever consulted for `fal-preferred` slides. */
  pexelsQuery?: (m: PptDeckImageMeta) => string;
};

/**
 * Every image slide, in deck order.
 *
 * Note indices 1, 7 and 9 previously carried a `pexelsQuery` and so quietly served stock photos
 * whenever Fal failed — which, given Fal failures were themselves invisible, is why the product
 * appeared to "use Pexels instead of Fal".
 */
const DECK_IMAGE_SPECS: readonly DeckImageSpec[] = [
  { idx: 0, slideNumber1Based: 1, falSlot: "title_slide_fal_fallback", provider: "fal-preferred", pexelsQuery: titleSlidePexelsQuery },
  { idx: 1, slideNumber1Based: 2, falSlot: "fallback_pexels_starter", provider: "fal-required" },
  { idx: 2, slideNumber1Based: 3, falSlot: "sdg_chapter", provider: "fal-preferred" },
  { idx: 5, slideNumber1Based: 6, falSlot: "main_teaching", provider: "fal-preferred" },
  { idx: 6, slideNumber1Based: 7, falSlot: "differentiated_activity", provider: "fal-required" },
  { idx: 7, slideNumber1Based: 8, falSlot: "fallback_pexels_uae", provider: "fal-required" },
  { idx: 8, slideNumber1Based: 9, falSlot: "fallback_pexels_plenary", provider: "fal-preferred", pexelsQuery: () => "reflection classroom learning summary" },
  { idx: 9, slideNumber1Based: 10, falSlot: "fallback_pexels_extended", provider: "fal-required" },
  { idx: 10, slideNumber1Based: 11, falSlot: "exit_ticket", provider: "fal-preferred" },
  { idx: 11, slideNumber1Based: 12, falSlot: "success_criteria", provider: "fal-preferred" },
];

/** Exported so tests can assert the policy directly rather than inferring it from behaviour. */
export function getDeckImageProviderPolicy(deckIndex: number): SlideImageProviderPolicy | undefined {
  return DECK_IMAGE_SPECS.find((s) => s.idx === deckIndex)?.provider;
}

export function pexelsIsAllowedForDeckIndex(deckIndex: number): boolean {
  const spec = DECK_IMAGE_SPECS.find((s) => s.idx === deckIndex);
  return Boolean(spec && spec.provider === "fal-preferred" && spec.pexelsQuery);
}

/** What actually happened for one slide — kept for server-side diagnostics. */
export type SlideImageDiagnostic = {
  deckIndex: number;
  slideNumber1Based: number;
  policy: SlideImageProviderPolicy;
  resolvedProvider: "fal" | "pexels" | "none";
  falFailureKind?: FalImageFailureKind;
  falFailureReason?: string;
};

export type PptDeckImageGenerationResult = {
  urls: (string | null)[];
  notices: string[];
  diagnostics: SlideImageDiagnostic[];
};

/**
 * Records Fal failures where they can actually be seen.
 *
 * Teacher-facing notices deliberately stay free of vendor names (`image-notices.ts` filters
 * them), so the diagnostic channel is the server: Sentry plus `console.error`, which survives
 * the production `removeConsole` that strips `console.log`.
 */
function recordFalFailure(d: SlideImageDiagnostic, meta: PptDeckImageMeta): void {
  console.error(
    `[ppt-deck-images] slide ${d.slideNumber1Based} (deck[${d.deckIndex}], ${d.policy}) ` +
      `got no fal image - ${d.falFailureKind}: ${d.falFailureReason}`,
  );
  if (d.policy === "fal-required") {
    Sentry.captureException(
      new Error(`fal image missing for required slide ${d.slideNumber1Based}`),
      {
        tags: {
          area: "ppt-images",
          provider: "fal",
          falFailureKind: d.falFailureKind ?? "unknown",
          deckIndex: String(d.deckIndex),
        },
        extra: {
          reason: d.falFailureReason,
          subject: meta.subject,
          grade: meta.grade,
          topic: meta.topic,
        },
      },
    );
  }
}

type ResolvedSlot = {
  spec: DeckImageSpec;
  label: string;
  url: string | null;
  diag: SlideImageDiagnostic;
};

export async function generatePptDeckSlideImages(
  meta: PptDeckImageMeta,
): Promise<PptDeckImageGenerationResult> {
  const deckLen = STRUCTURED_LESSON_DECK_SLIDE_COUNT;
  const deck: (string | null)[] = Array.from({ length: deckLen }, () => null);
  const used = new Set<string>();
  const notices: string[] = [];
  const diagnostics: SlideImageDiagnostic[] = [];

  const falOk = Boolean(getFalCredentials());
  const falCircuit = getFalPptCircuitOpenReason();
  const pexelsOk = Boolean(resolvePexelsApiKey());

  console.error(
    `[ppt-deck-images] start - subject="${meta.subject}", topic="${meta.topic}", deck=${deckLen}, ` +
      `fal=${falOk ? "ready" : "missing"}, falCircuitOpen=${falCircuit ? "YES" : "NO"}, ` +
      `pexelsFallback=${pexelsOk ? "ready" : "missing"}`,
  );
  if (pexelsOk) logPexelsEnvStatus("ppt-deck-pexels-fallback");

  if (!falOk || falCircuit) {
    notices.push(
      falCircuit ??
        "Fal AI image generation is not configured (FAL_API_KEY missing) — slide images will be limited.",
    );
  }

  // Resolved in parallel: each fal call can take up to FAL_IMAGE_TIMEOUT_MS, and running the
  // ten sequentially made a bad fal day cost minutes of lesson-creation latency.
  const resolved = await Promise.all(
    DECK_IMAGE_SPECS.map(async (spec): Promise<ResolvedSlot> => {
      const label = PEXELS_SLIDE_LABELS[spec.idx] ?? `slide-${spec.slideNumber1Based}`;
      const diag: SlideImageDiagnostic = {
        deckIndex: spec.idx,
        slideNumber1Based: spec.slideNumber1Based,
        policy: spec.provider,
        resolvedProvider: "none",
      };

      if (falOk && !falCircuit) {
        const outcome = await generateLessonPptFluxImageDeduped(
          { ...meta, lessonContentSnippet: meta.slideContentByIndex?.[spec.idx] ?? undefined },
          spec.falSlot,
          used,
          { verboseLog: true, logLabel: label },
        );
        if (outcome.ok) {
          // Reserve immediately so concurrent slots actually see it. Previously the shared set
          // was only filled after Promise.all resolved, making dedup a no-op.
          used.add(outcome.url);
          diag.resolvedProvider = "fal";
          return { spec, label, url: outcome.url, diag };
        }
        diag.falFailureKind = outcome.kind;
        diag.falFailureReason = outcome.reason;
      } else {
        diag.falFailureKind = falCircuit ? "circuit-open" : "not-configured";
        diag.falFailureReason = falCircuit ?? "fal credentials are not configured";
      }

      recordFalFailure(diag, meta);

      // Fal did not produce an image. For a fal-required slide the answer is "no image",
      // never a stock substitute that would disguise the failure as a success.
      if (spec.provider === "fal-required") {
        return { spec, label, url: null, diag };
      }

      if (spec.pexelsQuery && pexelsOk) {
        const q = spec.pexelsQuery(meta);
        console.error(
          `[ppt-deck-images] ${label} falling back to Pexels (policy=fal-preferred) query="${q}"`,
        );
        const url = await fetchPexelsUniqueLandscapeUrl(q, used, {
          verboseLog: true,
          logLabel: `${label}-pexels-fallback`,
          slideNumber1Based: spec.slideNumber1Based,
        });
        if (url) {
          used.add(url);
          diag.resolvedProvider = "pexels";
          return { spec, label, url, diag };
        }
      }
      return { spec, label, url: null, diag };
    }),
  );

  for (const { spec, label, url, diag } of resolved) {
    diagnostics.push(diag);
    if (url) {
      deck[spec.idx] = url;
    } else {
      console.warn(
        `[ppt-deck-images] deck[${spec.idx}] slide ${spec.slideNumber1Based} (${label}) - NO IMAGE`,
      );
    }
  }

  const missingRequired = diagnostics.filter(
    (d) => d.policy === "fal-required" && d.resolvedProvider !== "fal",
  );
  if (missingRequired.length > 0) {
    console.error(
      `[ppt-deck-images] ${missingRequired.length} fal-required slide(s) have no generated image: ` +
        missingRequired.map((d) => `slide ${d.slideNumber1Based} (${d.falFailureKind})`).join(", "),
    );
  }

  const got = deck.filter(Boolean).length;
  console.error(`[ppt-deck-images] done - ${got}/${DECK_IMAGE_SPECS.length} slots filled`);

  return { urls: deck, notices, diagnostics };
}

/** @deprecated Prefer generatePptDeckSlideImages during lesson creation. */
export async function fetchPptImagesWithFallback(
  topic: string,
  subject: string,
  grade: string,
  deckSize: number,
): Promise<(string | null)[]> {
  const { urls } = await generatePptDeckSlideImages({ topic, subject, grade });
  if (deckSize === urls.length) return urls;
  return Array.from({ length: deckSize }, (_, i) => urls[i] ?? null);
}
