import type { Metadata } from "next";
import { LegalPageLayout, LegalSection } from "@/components/legal/legal-page-layout";

export const metadata: Metadata = {
  title: "Terms of Service | Layah.ai",
  description:
    "Terms of Service for Layah.ai — AI lesson planning and classroom tools for teachers and schools.",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="August 7, 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of Layah.ai
        (&quot;Layah,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) at{" "}
        <a href="https://layah.in" className="font-medium underline" style={{ color: "var(--brand)" }}>
          layah.in
        </a>{" "}
        and related services (the &quot;Service&quot;). By creating an account or using the Service, you
        agree to these Terms.
      </p>

      <LegalSection title="1. Eligibility and accounts">
        <p>
          The Service is designed for teachers, educators, and authorized school personnel. You must
          provide accurate registration information and keep your credentials secure. You are
          responsible for all activity under your account.
        </p>
        <p>
          We may limit accounts to one active session at a time for security. You must not share login
          credentials in ways that violate these Terms or your institution&apos;s policies.
        </p>
      </LegalSection>

      <LegalSection title="2. Description of the Service">
        <p>
          Layah provides AI-assisted tools to help educators create lesson plans, presentations,
          worksheets, question papers, differentiated materials, and related classroom resources. Features
          and availability may change over time. Free and paid plans may include usage limits as described
          on our pricing page.
        </p>
      </LegalSection>

      <LegalSection title="3. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Use the Service for any unlawful purpose or in violation of applicable education or data laws</li>
          <li>Upload content that infringes intellectual property or privacy rights of others</li>
          <li>Submit sensitive student personal data without proper authorization and safeguards</li>
          <li>Attempt to reverse engineer, scrape, overload, or disrupt the Service</li>
          <li>Resell, sublicense, or commercially exploit the Service without our written consent</li>
          <li>Use outputs to mislead others about authorship where disclosure is required by your employer or law</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. AI-generated content">
        <p>
          Outputs are generated by artificial intelligence and may be inaccurate, incomplete, or
          inappropriate for your context. You must review, edit, and approve all materials before using
          them with students. Layah does not guarantee curriculum compliance, exam accuracy, or fitness
          for a particular classroom.
        </p>
        <p>
          You retain responsibility for how generated content is used in your teaching practice.
        </p>
      </LegalSection>

      <LegalSection title="5. Your content and intellectual property">
        <p>
          You retain ownership of content you submit, subject to the license below. You grant Layah a
          non-exclusive, worldwide license to host, process, and display your content solely to operate
          and improve the Service and provide features you request.
        </p>
        <p>
          Layah&apos;s brand, software, designs, and proprietary materials remain our property. You may not
          copy or use our trademarks without permission.
        </p>
      </LegalSection>

      <LegalSection title="6. Subscriptions and payments">
        <p>
          Payments are processed by Razorpay, our third-party payment provider, and are charged in
          Indian Rupees (INR) regardless of what currency is displayed to you elsewhere on the Service.
          We do not store your full card, UPI, or bank details — Razorpay handles this in accordance
          with its own security standards and applicable payment regulations.
        </p>
        <p>
          <strong>Auto-renewal (Pro Monthly).</strong> The Pro Monthly plan is a recurring subscription
          that automatically renews every 30 days at the then-current price, charged to your saved
          payment method, until you cancel. By subscribing, you authorize us and Razorpay to make these
          recurring charges. You will be notified before each renewal charge as required by applicable
          payment regulations.
        </p>
        <p>
          <strong>Cancelling auto-renewal.</strong> You can cancel anytime from Settings → Manage
          Subscription. Cancellation stops future charges but takes effect at the end of your current
          paid 30-day period — you keep Pro access until then, and we do not provide partial refunds
          for the unused portion of a period.
        </p>
        <p>
          <strong>Failed renewal payments.</strong> If a renewal charge fails (for example, an expired
          card), we will not immediately remove your access. Razorpay will automatically retry the
          charge for a grace period; if all retries fail, your account will be downgraded to the Free
          plan.
        </p>
        <p>
          <strong>One-time purchases.</strong> Annual Pro, Pro Plus, and School plans are charged as a
          single one-time payment for the selected period and do not auto-renew unless we tell you
          otherwise at checkout.
        </p>
        <p>
          Fees are otherwise non-refundable except where required by law or explicitly stated. We may
          change pricing with reasonable notice before your next renewal; changes do not apply
          retroactively to a period you have already paid for.
        </p>
        <p>
          School and enterprise plans may be subject to separate agreements.
        </p>
      </LegalSection>

      <LegalSection title="7. Privacy">
        <p>
          Our collection and use of personal information is described in our{" "}
          <a href="/privacy" className="font-medium underline" style={{ color: "var(--brand)" }}>
            Privacy Policy
          </a>
          , which is incorporated into these Terms by reference.
        </p>
      </LegalSection>

      <LegalSection title="8. Disclaimers">
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY
          KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
          AND NON-INFRINGEMENT. WE DO NOT WARRANT UNINTERRUPTED OR ERROR-FREE OPERATION.
        </p>
      </LegalSection>

      <LegalSection title="9. Limitation of liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, LAYAH AND ITS AFFILIATES, OFFICERS, AND SUPPLIERS WILL
          NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR
          ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE.
        </p>
        <p>
          OUR TOTAL LIABILITY FOR ANY CLAIM RELATING TO THE SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID
          US IN THE TWELVE (12) MONTHS BEFORE THE CLAIM, OR ONE HUNDRED US DOLLARS (USD $100), WHICHEVER IS
          GREATER.
        </p>
      </LegalSection>

      <LegalSection title="10. Indemnification">
        <p>
          You agree to indemnify and hold Layah harmless from claims arising out of your use of the
          Service, your content, or your violation of these Terms or applicable law.
        </p>
      </LegalSection>

      <LegalSection title="11. Termination">
        <p>
          You may stop using the Service at any time. We may suspend or terminate your access if you
          breach these Terms, pose a security risk, or as required by law. Upon termination, your right to
          use the Service ends; provisions that by nature should survive will remain in effect.
        </p>
      </LegalSection>

      <LegalSection title="12. Governing law">
        <p>
          These Terms are governed by the laws of the United Arab Emirates, without regard to conflict of
          law principles, except where mandatory local consumer protections apply. Disputes will be
          resolved in the courts of competent jurisdiction in the UAE, unless otherwise required by law.
        </p>
      </LegalSection>

      <LegalSection title="13. Changes to these Terms">
        <p>
          We may modify these Terms from time to time. We will post updates on this page and revise the
          &quot;Last updated&quot; date. Material changes may be communicated by email or in-app notice.
          Continued use after changes constitutes acceptance.
        </p>
      </LegalSection>

      <LegalSection title="14. Contact">
        <p>
          Questions about these Terms? Contact{" "}
          <a
            href="mailto:support@layah.in"
            className="font-medium underline"
            style={{ color: "var(--brand)" }}
          >
            support@layah.in
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
